server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:db}}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}

    show-sql: ${JPA_SHOW_SQL:true}

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}

  output:
    ansi:
      enabled: always

app:
  api:
    base-url-api: ${APP_BASE_URL:${RENDER_EXTERNAL_URL:http://localhost:8080}}
    title: ${APP_TITLE:MasterBranch - backend  Interview Questions 2026}
    version: ${APP_VERSION:1.0.0}
    description: ${APP_DESCRIPTION:API quản lý lịch và kiểm tra khung giờ trống}
    contact-name: ${APP_CONTACT_NAME:MasterBranch Team}
    contact-email: ${APP_CONTACT_EMAIL:ngtbang2264.dev@gmail.com}
    swagger:
      enable: ${SWAGGER_ENABLE:true}

logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_BINDER:TRACE}
